export const navigation = [
  {
    label: "运行总览",
    detail: "查看用量、费用与请求趋势",
    icon: "overview",
    path: "/",
    group: "工作空间",
    component: () => import("../pages/Overview.vue"),
  },
  {
    label: "调用记录",
    detail: "筛选请求，检查执行详情",
    icon: "activity",
    path: "/calls",
    group: "工作空间",
    component: () => import("../pages/Calls.vue"),
  },
  {
    label: "Routers",
    detail: "管理 Routers 与候选顺序",
    icon: "routes",
    path: "/routes",
    group: "管理",
    component: () => import("../pages/Routes.vue"),
  },
  {
    label: "Providers",
    detail: "管理连接、模型与价格",
    icon: "providers",
    path: "/providers",
    group: "管理",
    component: () => import("../pages/Providers.vue"),
  },
  {
    label: "请求实验室",
    detail: "发送请求，验证模型接入",
    icon: "lab",
    path: "/playground",
    group: "工作空间",
    component: () => import("../pages/Playground.vue"),
  },
  {
    label: "系统设置",
    detail: "服务、日志与熔断策略",
    icon: "settings",
    path: "/settings",
    group: "管理",
    component: () => import("../pages/Settings.vue"),
  },
] as const;
